---
AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudformation template to create Cloudera Resources

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select a VPC with Subnets covering 2 Availability zone at least.
    MinLength: 1

Resources:
  ClouderaHbase2TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      Name: HBase-Master-2
      TargetType: instance
      VpcId: !Ref VpcId
      Targets:
        - Id: i-0b9c6b3ab3bf55f26
          Port: 16010

  ClouderaHbase3TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      Name: HBase-Master-3
      TargetType: instance
      VpcId: !Ref VpcId
      Targets:
        - Id: i-0181a59e1d41114d4
          Port: 16010

  ClouderaHdfsTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      Name: HDFS
      TargetType: instance
      VpcId: !Ref VpcId
      Targets:
        - Id: i-0c2080fc1f5bf88f5
          Port: 9870

  ClouderaHiveTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      Name: Hive
      TargetType: instance
      VpcId: !Ref VpcId
      Targets:
        - Id: i-0291efea65f611d43
          Port: 10002

  ClouderaHueTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      Name: Hue
      TargetType: instance
      VpcId: !Ref VpcId
      Targets:
        - Id: i-0291efea65f611d43
          Port: 8889

  ClouderaImpalaStateStoreTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      Name: Impala-StateStore
      TargetType: instance
      VpcId: !Ref VpcId
      Targets:
        - Id: i-056fba1a84e21dda2
          Port: 25010

  ClouderaImpalaCatalogTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      Name: Impala-catalog
      TargetType: instance
      VpcId: !Ref VpcId
      Targets:
        - Id: i-056fba1a84e21dda2
          Port: 25020

  ClouderaImpalaDaemon1TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      Name: Impala-daemon-1
      TargetType: instance
      VpcId: !Ref VpcId
      Targets:
        - Id: i-0a56b62e7f90cd6c4
          Port: 25000

  ClouderaImpalaDaemon2TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      Name: Impala-daemon-2
      TargetType: instance
      VpcId: !Ref VpcId
      Targets:
        - Id: i-0a727858186f53239
          Port: 25000

  ClouderaImpalaDaemon3TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      Name: Impala-daemon-3
      TargetType: instance
      VpcId: !Ref VpcId
      Targets:
        - Id: i-00c2604ef7379f2f4
          Port: 25000

  ClouderaOozieTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      Name: Oozie
      TargetType: instance
      VpcId: !Ref VpcId
      Targets:
        - Id: i-056fba1a84e21dda2
          Port: 11000

  ClouderaSparkTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      Name: Spark
      TargetType: instance
      VpcId: !Ref VpcId
      Targets:
        - Id: i-0181a59e1d41114d4
          Port: 18088

  ClouderaYarnHistoryTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      Name: Yarn-History
      TargetType: instance
      VpcId: !Ref VpcId
      Targets:
        - Id: i-0c2080fc1f5bf88f5
          Port: 19888

  ClouderaKuduMaster1Group:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      Name: Kudu-Master-1
      TargetType: instance
      VpcId: !Ref VpcId
      Targets:
        - Id: i-0c2080fc1f5bf88f5
          Port: 8051

  ClouderaKuduMaster2Group:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      Name: Kudu-Master-2
      TargetType: instance
      VpcId: !Ref VpcId
      Targets:
        - Id: i-0b9c6b3ab3bf55f26
          Port: 8051

  ClouderaKuduMaster3Group:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      Name: Kudu-Master-3
      TargetType: instance
      VpcId: !Ref VpcId
      Targets:
        - Id: i-0181a59e1d41114d4
          Port: 8051