Resources:
  ClouderaAlertReceiverTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Protocol: email
          Endpoint: kaiqi.yu@ascendingdc.com

  ClouderaMaxNetworkinAlerm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: Cloudera-max-Networkin-alerm-cfm
      ActionsEnabled: true
      OKActions: []
      AlarmActions:
        - !Ref ClouderaAlertReceiverTopic
      InsufficientDataActions: []
      Dimensions: []
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 50000000
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Metrics:
        - Id: e1
          Label: Cloudera-max-Networkin
          ReturnData: true
          Expression: MAX([m1, m2, m3, m4, m5, m6, m7, m8])
        - Id: m1
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/EC2
              MetricName: NetworkIn
              Dimensions:
                - Name: InstanceId
                  Value: i-01611f2d40e38d03c
            Period: 60
            Stat: Average
        - Id: m2
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/EC2
              MetricName: NetworkIn
              Dimensions:
                - Name: InstanceId
                  Value: i-0cd42200e37b68a15
            Period: 60
            Stat: Average
        - Id: m3
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/EC2
              MetricName: NetworkIn
              Dimensions:
                - Name: InstanceId
                  Value: i-0b1f937767ad38819
            Period: 60
            Stat: Average
        - Id: m4
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/EC2
              MetricName: NetworkIn
              Dimensions:
                - Name: InstanceId
                  Value: i-0c5e5f01fa15a6c72
            Period: 60
            Stat: Average
        - Id: m5
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/EC2
              MetricName: NetworkIn
              Dimensions:
                - Name: InstanceId
                  Value: i-03ba61764408c3b85
            Period: 60
            Stat: Average
        - Id: m6
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/EC2
              MetricName: NetworkIn
              Dimensions:
                - Name: InstanceId
                  Value: i-0db3135144959852f
            Period: 60
            Stat: Average
        - Id: m7
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/EC2
              MetricName: NetworkIn
              Dimensions:
                - Name: InstanceId
                  Value: i-01234d15917873831
            Period: 60
            Stat: Average
        - Id: m8
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/EC2
              MetricName: NetworkIn
              Dimensions:
                - Name: InstanceId
                  Value: i-06533a3aabeaf7adc
            Period: 60
            Stat: Average

  ClouderaMaxNetworkoutAlerm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: Cloudera-max-Networkout-alerm-cfm
      ActionsEnabled: true
      OKActions: []
      AlarmActions:
        - !Ref ClouderaAlertReceiverTopic
      InsufficientDataActions: []
      Dimensions: []
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 50000000
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Metrics:
        - Id: e1
          Label: Cloudera-max-Networkout
          ReturnData: true
          Expression: MAX([m1, m2, m3, m4, m5, m6, m7, m8])
        - Id: m1
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/EC2
              MetricName: NetworkOut
              Dimensions:
                - Name: InstanceId
                  Value: i-01611f2d40e38d03c
            Period: 60
            Stat: Average
        - Id: m2
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/EC2
              MetricName: NetworkOut
              Dimensions:
                - Name: InstanceId
                  Value: i-0cd42200e37b68a15
            Period: 60
            Stat: Average
        - Id: m3
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/EC2
              MetricName: NetworkOut
              Dimensions:
                - Name: InstanceId
                  Value: i-0b1f937767ad38819
            Period: 60
            Stat: Average
        - Id: m4
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/EC2
              MetricName: NetworkOut
              Dimensions:
                - Name: InstanceId
                  Value: i-0c5e5f01fa15a6c72
            Period: 60
            Stat: Average
        - Id: m5
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/EC2
              MetricName: NetworkOut
              Dimensions:
                - Name: InstanceId
                  Value: i-03ba61764408c3b85
            Period: 60
            Stat: Average
        - Id: m6
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/EC2
              MetricName: NetworkOut
              Dimensions:
                - Name: InstanceId
                  Value: i-0db3135144959852f
            Period: 60
            Stat: Average
        - Id: m7
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/EC2
              MetricName: NetworkOut
              Dimensions:
                - Name: InstanceId
                  Value: i-01234d15917873831
            Period: 60
            Stat: Average
        - Id: m8
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/EC2
              MetricName: NetworkOut
              Dimensions:
                - Name: InstanceId
                  Value: i-06533a3aabeaf7adc
            Period: 60
            Stat: Average

  ClouderaMaxCPUUtilizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: Cloudera-max-CPUUtilization-alarm-cfm
      ActionsEnabled: true
      OKActions: []
      AlarmActions:
        - !Ref ClouderaAlertReceiverTopic
      InsufficientDataActions: []
      Dimensions: []
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 75
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Metrics:
        - Id: e1
          Label: Cloudera-max-CPUUtilization
          ReturnData: true
          Expression: MAX([m1, m2, m3, m4, m5, m6, m7, m8])
        - Id: m1
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/EC2
              MetricName: CPUUtilization
              Dimensions:
                - Name: InstanceId
                  Value: i-01611f2d40e38d03c
            Period: 60
            Stat: Average
        - Id: m2
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/EC2
              MetricName: CPUUtilization
              Dimensions:
                - Name: InstanceId
                  Value: i-0cd42200e37b68a15
            Period: 60
            Stat: Average
        - Id: m3
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/EC2
              MetricName: CPUUtilization
              Dimensions:
                - Name: InstanceId
                  Value: i-0b1f937767ad38819
            Period: 60
            Stat: Average
        - Id: m4
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/EC2
              MetricName: CPUUtilization
              Dimensions:
                - Name: InstanceId
                  Value: i-0c5e5f01fa15a6c72
            Period: 60
            Stat: Average
        - Id: m5
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/EC2
              MetricName: CPUUtilization
              Dimensions:
                - Name: InstanceId
                  Value: i-03ba61764408c3b85
            Period: 60
            Stat: Average
        - Id: m6
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/EC2
              MetricName: CPUUtilization
              Dimensions:
                - Name: InstanceId
                  Value: i-0db3135144959852f
            Period: 60
            Stat: Average
        - Id: m7
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/EC2
              MetricName: CPUUtilization
              Dimensions:
                - Name: InstanceId
                  Value: i-01234d15917873831
            Period: 60
            Stat: Average
        - Id: m8
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/EC2
              MetricName: CPUUtilization
              Dimensions:
                - Name: InstanceId
                  Value: i-06533a3aabeaf7adc
            Period: 60
            Stat: Average
