---

- name: test
  hosts: cloudera
  gather_facts: false
  remote_user: ec2-user
  become: True
  tasks:
    - include_vars: UserInfo.yaml

    - name: Add a new student user
      user:
        name: "{{ item.username }}"
        groups: "{{ item.group }}"
        shell: /bin/bash
        append: yes
        # state: absent
        # remove: yes
      with_items: '{{users}}'

    - name: Add authorized keys
      authorized_key:
        user: "{{ item.username }}"
        state: present
        key: "{{ item.pub }}"
      with_items: '{{users}}'